default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: mysql2
  database: test_project_db
  username: root
  password: root
  host: localhost

test:
  adapter: mysql2
  database: test_project_db_test
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  database: library_production
  username: root
  password: root
  host: localhost

